// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mhtest.Models
{
    public partial class Student
    {
        public Student()
        {
            Scores = new HashSet<Score>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int Age { get; set; }
        public string Lastname { get; set; }

        public virtual ICollection<Score> Scores { get; set; }
    }
}